中间件是一种独立的系统软件或服务程序，分布式应用软件借助这种软件在不同的技术之间共享资源，中间件位于客户机服务器的操作系统之上，
管理计算资源和网络通信，也可以定义为网络环境下处于操作系统、数据库等系统软件和应用软件之间的一种起连接作用的分布式软件，
主要解决异构网络环境下分布式应用软件的互连与互操作问题，提供标准接口、协议，屏蔽实现细节，提高应用系统易移植性。


作用
　中间件通过提供简单、一致、集成的开发和运行环境，简化分布式系统的设计、编程和管理

从功能性外延来看，中间件包括交易中间件、消息中间件、集成中间件等各种功能性的中间件技术和产品.
三大类产品：应用服务类中间件、应用集成类中间件、业务架构类中间件。

** 在Java web开发的演进与进化中，我们对于消息系统，数据库，服务化接口的抽象等，涉及数据分离的过程中，
在分离过程中，就会涉及到分离后系统间，数据库间的交互。
java中间件就是处理我们数据间交互，连接数据分离后两个系统间的通信，中间件不属于任何一个开发项目，
就是让我们对应系统间或者数据库间数据流通无感知。有点像Linux下的管道。

在java web开发中适用的范围主要应该是下面三个领域：

远程过程调用和对象访问中间件

主要解决分布式环境下应用的互相访问问题，这也是支撑应用服务化功能的基础；
例如：RPC：Remote Process Call（远程过程调用中间件）
消息中间件：解决应用之间的消息传递、解耦、异步的问题。
例如：ActiveMQ 是Apache出品，最流行的，能力强劲的开源消息总线。ActiveMQ 是一个完全支持JMS1.1和J2EE 1.4规范的 JMS Provider实现。


数据访问中间件

主要解决应用访问数据库的共性问题的组件
例如：数据访问中间间就是我们使用数据库指定的数据驱动，例如：ODBC JDBC，以 JDBC 为例，数据库本地维护了一个数据访问中间件，
我们在访问数据库的时候，配置的地址其实是直接连接到JDBC这个数据访问中间件，如果我们执行查询数据，
或者对数据库的操作都是通过JDBC来连接数据库，然后通过JDBC查询完成数据库以后再返回给我们应用程序。
作为中间件，查询过程对于我们是不可知的。

java常用的中间件

tomcat
Weblogic
JBOSS
Coldfusion
Websphere
GlassFish
(web服务器中间件)
一般本地开发的话建议使用tomcat。

linux系统建议使用jetty或apache hpptd

大型的项目就用JBOSS或webloigc

小项目，或者是个人开发tomcat 大项目或者商业项目一般采用：weblgoic/webshere
其他的还有jboss、glasshfish等
一些示例项目或者小项目常采用jetty

JBoss是一个运行EJB的J2EE应用服务器。它是开放源代码的项目，遵循最新的J2EE规范。从JBoss项目开始至今
，它已经从一个EJB容器发展成为一个基于的J2EE的一个web 操作系统（operating system for web），
它体现了J2EE规范中最新的技术

WebLogic服务器是企业级的应用服务器，支持EJB, 集群以及 ERP（企业资源计划）的连通性 ，开发公司：BEA。

WebSphere产品系列是IBM公司一套典型的电子商务应用开发工具及运行环境

MyCat
    MyCat是一个基于MySQL的分表分库的中间件软件，也可以说是一个分布式数据库，其前身为阿里巴巴开源的Cobar，
    但由于阿里巴巴后来发展云平台并提供收费RDS服务，因此最终关闭了这个开源项目。然后国内一帮技术大拿一起发起了MyCat开源项目
    ( http : / / www my cat org. cn ），目标是成为Apache旗下的顶级中国开源项目。

MyCat是一个开源的分布式数据库系统，是一个实现了MySQL协议的服务器，前端用户可以把它看作是一个数据库代理，
用MySQL客户端工具和命令行访问，而其后端可以用MySQL原生协议与多个MySQL服务器通信，
也可以用JDBC协议与大多数主流数据库服务器通信，其核心功能是分表分库，即将一个大表水平分割为N个小表，
存储在后端MySQL服务器里或者其他数据库里。
----
当我们的应用只需要一台数据库服务器的时候我们并不需要Mycat，而如果你需要分库甚至分表，这时候应用要面对很多个数据库的时候，
这个时候就需要对数据库层做一个抽象，来管理这些数据库，而最上面的应用只需要面对一个数据库层的抽象或者说数据库中间件就好了，
这就是Mycat的核心作用。

应用场景
Mycat发展到现在，适用的场景已经很丰富，而且不断有新用户给出新的创新性的方案，以下是几个典型的应用场景：
单纯的读写分离，此时配置最为简单，支持读写分离，主从切换
分表分库，对于超过1000万的表进行分片，最大支持1000亿的单表分片
多租户应用，每个应用一个库，但应用程序只连接Mycat，从而不改造程序本身，实现多租户化
报表系统，借助于Mycat的分表能力，处理大规模报表的统计
替代Hbase，分析大数据
作为海量数据实时查询的一种简单有效方案，比如100亿条频繁查询的记录需要在3秒内查询出来结果，除了基于主键的查
询，还可能存在范围查询或其他属性查询，此时Mycat可能是最简单有效的选择
----
mycat不适应的场景
https://blog.csdn.net/gaobudong1234/article/details/79581846

1. mycat例如 ：分片方法为 id 值取 3 的模，根据模值确定在DB1，DB2，DB3中的某个分片，此时id为分片字段
如果查询条件中没有 分片字段 条件，即没有where id=××× 的条件，Mycat无法计算路由，便发送到所有节点上执行
所以 如果设计使用Mycat时有非分片字段查询，请考虑放弃！
2. Mycat在处理 有偏移量的排序分页 时是另外一套逻辑——改写SQL 。
Mycat在下发有 limit m,n 的SQL语句时会对其进行改写，改写成 limit 0, m+n 来保证查询结果的逻辑正确性
也就是说，对于有 t 个DB节点的全分片 limit m, n 操作，Mycat需要处理的数据量为 (m+n)*t 个。
比如实际应用中有50个DB节点，要执行limit 1000,10操作，则Mycat处理的数据量为 50500 条，返回结果集为10，
当偏移量更大时，内存和CPU资源的消耗则是数十倍增加。

如果设计使用Mycat时有分页排序，请考虑放弃！

3. 当join SQL在各个单独的分片DB中都查不出结果，也就是说Mycat不能查询出正确的结果集。

设计使用Mycat时如果要进行表JOIN操作，要确保两个表的关联字段具有相同的数据分布，否则请考虑放弃！

4. 设计使用Mycat时如果有分布式事务，得先看是否得保证事务得强一致性，否则请考虑放弃！

https://blog.csdn.net/xiaoliuliu2050/article/details/53375839
zookeeper
kafka
