1. @Cacheable注解可以用在方法或者类级别。当他应用于方法级别的时候，就是缓存返回值了。当应用在类级别的时候，这个类的所有方法的返回值都将被缓存。

2. @Cacheable注解有三个参数，value是必须的，还有key和condition。第一个参数，也就是value指明了缓存将被存到什么地方。
任何存储在缓存中的数据为了高速访问都需要一个key。Spring默认使用被@Cacheable注解的方法的签名来作为key，当然你可以重写key，自定义key可以使用SpEL表达式。

. @Cacheable({"cache1", "cache2"})//Cache是发生在cache1和cache2上的

*直接使用“#参数名”或者“#p参数index”*
. @Cacheable(value = "employee", key = "#surname")
   public Person findEmployeeBySurname(String firstName, String surname, int age) {

    return new Person(firstName, surname, age);
  }
在findEmployeeBySurname()的注解中”#surname”是一个SpEL表达式，他将使用findEmployeeBySurname()方法中的surname参数作为key。
----
@Cacheable(value="users", key="#id")
//等同于  @Cacheable(value="users", key="#p0")
   public User find(Integer id) {
      return null;
   }

 @Cacheable(value="users", key="#user.id")
//等同于 @Cacheable(value="users", key="#p0.id")
   public User find(User user) {
      return null;
   }
----
最后一个参数是condition（可选），同样的，也是引用一个SpEL表达式。但是这个参数将指明方法的返回结果是否被缓存。
@Cacheable(value = "employee", condition = "#age < 25")
 public Person findEmployeeByAge(String firstName, String surname, int age) {

   return new Person(firstName, surname, age);
 }
上面的例子中，只有年龄小于25的时候才被缓存。

效果：第一次执行，会执行方法体;再次执行，Spring直接将缓存中的数据作为返回值返回
@Cacheable可以标记在一个方法上，也可以标记在一个类上。当标记在一个方法上时表示该方法是支持缓存的，当标记在一个类上时则表示该类所有的方法都是支持缓存的。
对于一个支持缓存的方法，Spring会在其被调用后将其返回值缓存起来，以保证下次利用同样的参数来执行该方法时可以直接从缓存中获取结果，而不需要再次执行该方法。
Spring在缓存方法的返回值时是以键值对进行缓存的，值就是方法的返回结果，至于键的话，Spring又支持两种策略，默认策略和自定义策略
*需要注意的是当一个支持缓存的方法在对象内部被调用时是不会触发缓存功能的。*

3. 使用@CacheEvict注解来清除缓存？
@CacheEvict是用来标注在需要清除缓存元素的方法或类上的。当标记在一个类上时表示其中所有的方法的执行都会触发缓存的清除操作。
@CacheEvict可以指定的属性有value、key、condition、allEntries和beforeInvocation。其中value、key和condition的语义与@Cacheable对应的属性类似。
即value表示清除操作是发生在哪些Cache上的（对应Cache的名称）；key表示需要清除的是哪个key，如未指定则会使用默认策略生成的key；condition表示清除操作发生的条件。

. allEntries是boolean类型，表示是否需要清除缓存中的所有元素。默认为false，表示不需要。当指定了allEntries为true时，Spring Cache将忽略指定的key。
有的时候我们需要Cache一下清除所有的元素，这比一个一个清除元素更有效率。
 @CacheEvict(value="users", allEntries=true)
. 清除操作默认是在对应方法成功执行之后触发的，即方法如果因为抛出异常而未能成功返回时也不会触发清除操作。使用beforeInvocation可以改变触发清除操作的时间，当我们指定该属性值为true时，Spring会在调用该方法之前清除缓存中的指定元素。
@CacheEvict(value="users", beforeInvocation=true)
netstat -lntp  查看端口号使用情况

4. @Caching注解可以让我们在一个方法或者类上同时指定多个Spring Cache相关的注解。其拥有三个属性：cacheable、put和evict，分别用于指定@Cacheable、@CachePut和@CacheEvict。
    例如：@Caching(cacheable = @Cacheable("users"), evict = { @CacheEvict("cache2"), @CacheEvict(value = "cache3", allEntries = true) })

5. Spring允许我们在配置可缓存的方法时使用自定义的注解，前提是自定义的注解上必须使用对应的注解进行标注。如我们有如下这么一个使用@Cacheable进行标注的自定义注解。
----
@Target({ElementType.TYPE, ElementType.METHOD})

@Retention(RetentionPolicy.RUNTIME)

@Cacheable(value="users")

public @interface MyCacheable {

}
----

<cache:annotation-driven/>有一个cache-manager属性用来指定当前所使用的CacheManager对应的bean的名称，默认是cacheManager，
所以当我们的CacheManager的id为cacheManager时我们可以不指定该参数，否则就需要我们指定了。

<cache:annotation-driven/>还可以指定一个mode属性，可选值有proxy和aspectj。默认是使用proxy。当mode为proxy时，只有缓存方法在外部被调用的时候Spring Cache才会发生作用，
这也就意味着如果一个缓存方法在其声明对象内部被调用时Spring Cache是不会发生作用的。而mode为aspectj时就不会有这种问题。另外使用proxy时，
只有public方法上的@Cacheable等标注才会起作用，如果需要非public方法上的方法也可以使用Spring Cache时把mode设置为aspectj。

此外，<cache:annotation-driven/>还可以指定一个proxy-target-class属性，表示是否要代理class，默认为false。我们前面提到的@Cacheable、@cacheEvict等也可以标注在接口上，
这对于基于接口的代理来说是没有什么问题的，但是需要注意的是当我们设置proxy-target-class为true或者mode为aspectj时，是直接基于class进行操作的，定义在接口上的@Cacheable
等Cache注解不会被识别到，那对应的Spring Cache也不会起作用了。

需要注意的是<cache:annotation-driven/>只会去寻找定义在同一个ApplicationContext下的@Cacheable等缓存注解


默认的key生成策略是通过KeyGenerator生成的，其默认策略如下：

n  如果方法没有参数，则使用0作为key。

n  如果只有一个参数的话则使用该参数作为key。

n  如果参数多余一个的话则使用所有参数的hashCode作为key。

























如何选择一个缓存的实现，并配置Spring的缓存？
https://blog.csdn.net/szwandcj/article/details/50240903
https://blog.csdn.net/zheng_sida/article/details/51539663
