=== java类加载器：

1. 启动（Bootstrap）类加载器：是用本地代码实现的类装入器，它负责将 <Java_Runtime_Home>/lib下面的类库加载到内存中（比如rt.jar）。由于引导类加载器涉及到虚拟机本地实现细节，
开发者无法直接获取到启动类加载器的引用，所以不允许直接通过引用进行操作。

2. 标准扩展（Extension）类加载器：是由 Sun 的 ExtClassLoader（sun.misc.Launcher$ExtClassLoader）实现的。它负责将< Java_Runtime_Home >/lib/ext或者由系统变量 java.ext.dir指定位置中的
类库加载到内存中。开发者可以直接使用标准扩展类加载器。

3. 系统（System）类加载器：是由 Sun 的 AppClassLoader（sun.misc.Launcher$AppClassLoader）实现的。它负责将系统类路径（CLASSPATH）中指定的类库加载到内存中。开发者可以直接使用系统类加载器。
除了以上列举的三种类加载器，还有一种比较特殊的类型 — 线程上下文类加载器。

*双亲委派机制描述*
某个特定的类加载器在接到加载类的请求时，首先将加载任务委托给父类加载器，依次递归，如果父类加载器可以完成类加载任务，就成功返回；只有父类加载器无法完成此加载任务时，才自己去加载。

==== 几点思考

1. Java虚拟机的第一个类加载器是Bootstrap，这个加载器很特殊，它不是Java类，因此它不需要被别人加载，它嵌套在Java虚拟机内核里面，也就是JVM启动的时候Bootstrap就已经启动，它是用C++写的二进制代码
（不是字节码），它可以去加载别的类。

这也是我们在测试时为什么发现System.class.getClassLoader()结果为null的原因，这并不表示System这个类没有类加载器，而是它的加载器比较特殊，是BootstrapClassLoader，由于它不是Java类，
因此获得它的引用肯定返回null。

2. 委托机制具体含义
当Java虚拟机要加载一个类时，到底派出哪个类加载器去加载呢？

首先当前线程的类加载器去加载线程中的第一个类（假设为类A）。
注：当前线程的类加载器可以通过Thread类的getContextClassLoader()获得，也可以通过setContextClassLoader()自己设置类加载器。
如果类A中引用了类B，Java虚拟机将使用加载类A的类加载器去加载类B。
还可以直接调用ClassLoader.loadClass()方法来指定某个类加载器去加载某个类。
委托机制的意义 — 防止内存中出现多份同样的字节码
比如两个类A和类B都要加载System类：

如果不用委托而是自己加载自己的，那么类A就会加载一份System字节码，然后类B又会加载一份System字节码，这样内存中就出现了两份System字节码。
如果使用委托机制，会递归的向父类查找，也就是首选用Bootstrap尝试加载，如果找不到再向下。这里的System就能在Bootstrap中找到然后加载，如果此时类B也要加载System，也从Bootstrap开始，
此时Bootstrap发现已经加载过了System那么直接返回内存中的System即可而不需要重新加载，这样内存中就只有一份System的字节码了。

使用双亲委派模型原因:java类随着其类加载器一起具备了一种带有优先级的层次关系.例如 java.lang.Object,无论哪一个类加载器要加载该类,最终都是委托给处于顶端的启动类加载器,因此object在程序的各种类加载器
环境中都是同一个类.相反如果没有使用双亲委派模型,那么假如用户自定义了一个称为java.lang.Object的类,并放在classPath中,那么系统将会出现多个不同的Object类,则java类型体系中最基础的行为都无法保证.

==== 类的加载方式

1）：本地编译好的class中直接加载
2）：网络加载：java.net.URLClassLoader可以加载url指定的类
3）：从jar、zip等等压缩文件加载类，自动解析jar文件找到class文件去加载util类
4）：从java源代码文件动态编译成为class文件

==== 类加载的时机

1. 类加载的生命周期：加载（Loading）-->验证（Verification）-->准备（Preparation）-->解析（Resolution）-->初始化（Initialization）-->使用（Using）-->卸载（Unloading）

2. 加载：这有虚拟机自行决定。

3. 初始化阶段：

a)遇到new、getstatic、putstatic、invokestatic这4个字节码指令时，如果类没有进行过初始化，出发初始化操作。

b)使用java.lang.reflect包的方法对类进行反射调用时。

c)当初始化一个类的时候，如果发现其父类还没有执行初始化则进行初始化。

d)虚拟机启动时用户需要指定一个需要执行的主类，虚拟机首先初始化这个主类。

注意：接口与类的初始化规则在第三点不同，接口不要气所有的父接口都进行初始化。
https://www.cnblogs.com/developer-ios/p/5550789.html

*如何定义个类加载器？你使用过哪些或者你在什么场景下需要定义的类加载器？*
https://www.cnblogs.com/szlbm/p/5504631.html
*Comparable和Comparator的区别*
http://www.cnblogs.com/szlbm/p/5504634.html
http://www.cnblogs.com/xrq730/p/4850140.html

PermSpace中保存什么数据? 会引起OutOfMemory吗？

PermSpace主要是存放静态的类信息和方法信息，静态的方法和变量，final标注的常量信息等。

当JVM需要加载一个新类的定义的却发现在PermGen没有足够的空间时，”java.lang.OutOfMemoryError: PermGen Space”错误便发生了。默认分配的永久代内存空间（PermGen Space），
服务器模式是64M，客户端模式是32M。有两个可能原因导致永久代内存空间问题。
第一个原因可能是你的应用程序或服务器拥有太多的类，而已有永久代内存空间不足以容纳所有的类。
https://blog.csdn.net/fengyie007/article/details/1780375
















==== 一道面试题

能不能自己写个类叫java.lang.System？

答案：通常不可以，但可以采取另类方法达到这个需求。
解释：为了不让我们写System类，类加载采用委托机制，这样可以保证爸爸们优先，爸爸们能找到的类，儿子就没有机会加载。而System类是Bootstrap加载器加载的，就算自己重写，也总是使用Java系统提供的System，
自己写的System类根本没有机会得到加载。

但是，我们可以自己定义一个类加载器来达到这个目的，为了避免双亲委托机制，这个类加载器也必须是特殊的。由于系统自带的三个类加载器都加载特定目录下的类，如果我们自己的类加载器放在一个特殊的目录，
那么系统的加载器就无法加载，也就是最终还是由我们自己的加载器加载。

*为什么需要自定义类加载器*:

1)加密:java代码可以轻易的被反编译,如果你需要对你的代码进行加密以防止反编译,可以先将编译后的代码用加密算法加密,类加密后就不能再使用java自带的类加载器了,这时候就需要自定义类加载器.

2)从非标准的来源加载代码:字节码是放在数据库,甚至是云端,就可以自定义类加载器,从指定来源加载类.


*自定义类加载器的方法*:

1、如果不想打破双亲委派模型，那么只需要重写findClass方法即可

2、如果想打破双亲委派模型，那么就重写整个loadClass方法
----
    private File getClassFile(String name)
    {
        File file = new File("D:/Person.class");//此处要提前编译Person类,并把class文件放到d盘下.

        return file;
    }
----
