{
  你在面月薪6000-8000的Java研发职位。面试官也知道JVM这么个大体概念，但知道的也不多。JVM这个概念本身就是“底层”。JVM有一条名为 instanceof 的指令，
  而Java源码编译到Class文件时会把Java语言中的 instanceof 运算符映射到JVM的 instanceof 指令上。你可以知道Java的源码编译器之一javac是这样做的：
  instanceof 是javac能识别的一个关键字，对应到Token.INSTANCEOF的token类型。做词法分析的时候扫描到"instanceof"关键字就映射到了一个Token.INSTANCEOF token。
  jdk7u/jdk7u/langtools: 5c9759e0d341 src/share/classes/com/sun/tools/javac/parser/Token.java该编译器的抽象语法树节点有一个JCTree.JCInstanceOf类用于表示instanceof运算。
  做语法分析的时候解析到instanceof运算符就会生成这个JCTree.JCInstanceof类型的节点。
  jdk7u/jdk7u/langtools: 5c9759e0d341 src/share/classes/com/sun/tools/javac/parser/JavacParser.java term2Rest()中途还得根据Java语言规范对instanceof运算符的编译时检查的规定
  把有问题的情况找出来。到最后生成字节码的时候为JCTree.JCInstanceof节点生成instanceof字节码指令。
  jdk7u/jdk7u/langtools: 5c9759e0d341 src/share/classes/com/sun/tools/javac/jvm/Gen.java visitTypeTest()（Java语言君说：“instanceof 这问题直接交给JVM君啦”）
  （面试官：你还给我废话⋯给我进情形3！）其实能回答到这层面就已经能解决好些实际问题了，例如说需要手工通过字节码增强来实现一些功能的话，知道JVM有这么条 instanceof 指令或许正好就能让你顺利的使用 ASM 之类的库完成工作。---------------------------------------------------------------------情形3：你在面月薪10000的Java高级研发职位。面试官对JVM有一些了解，想让你说说JVM会如何实现 instanceof 指令。但他可能也没看过实际的JVM是怎么做的，只是臆想过一下而已。JVM的规定就是“底层”。这种情况就给他JVM规范对 instanceof 指令的定义就好：Chapter 6. The Java Virtual Machine Instruction Set, JVM规范Java SE 7版根据规范来臆想一下实现就能八九不离十的混过这题了
}
A公司

那现在来聊一聊我所遇到的一些面试经历，希望给各位寻求新机会的小伙伴一个参考。总共面完5家收了4个offer，应该算是比较成功的吧。

由于种种原因，文中所涉及的公司均以代号标志，且我能告诉大家的也只有面试题，其他的不便透露细节，希望大家理解。

面试题

写出java中synchronized的使用方式。
{
https://blog.csdn.net/luoweifu/article/details/46613015
A. 无论synchronized关键字加在方法上还是对象上，如果它作用的对象是非静态的，则它取得的锁是对象；如果synchronized作用的对象是一个静态方法或一个类，则它取得的锁是对类，该类所有的对象同一把锁。
B. 每个对象只有一个锁（lock）与之相关联，谁拿到这个锁谁就可以运行它所控制的那段代码。
C. 实现同步是要很大的系统开销作为代价的，甚至可能造成死锁，所以尽量避免无谓的同步控制。


1.锁其实就是一个对象，当你拿到这个对象的使用权的时候，就可以去进行被锁住的代码了，反之不行。并不存在修饰一个类的说法吧。
2.“如果synchronized作用的对象是一个静态方法或一个类，则它取得的锁是对类，该类所有的对象同一把锁。”这句话是不对的，静态同步方法的锁是类的.Class对象，非静态同步方法的锁是当前的实例对象，二者没有关系，并不互斥。
PS：我参考楼主写的分析synchronized的文章http://blog.csdn.net/sted_zxz/article/details/76862444


一个线程访问一个对象的synchronized代码块时，别的线程可以访问该对象的非synchronized代码块而不受阻塞。

当有一个明确的对象作为锁时，就可以用类似下面这样的方式写程序。
public void method3(SomeObject obj)
{
   //obj 锁定的对象
   synchronized(obj)
   {
      // todo
   }
}

当没有明确的对象作为锁，只是想让一段代码同步时，可以创建一个特殊的对象来充当锁：
class Test implements Runnable
{
   private byte[] lock = new byte[0];  // 特殊的instance变量
   public void method()
   {
      synchronized(lock) {
         // todo 同步代码块
      }
   }

   public void run() {

   }
}//说明：零长度的byte数组对象创建起来将比任何对象都经济――查看编译后的字节码：生成零长度的byte[]对象只需3条操作码，而Object lock = new Object()则需要7行操作码。

synchronized关键字不能继承。
虽然可以使用synchronized来定义方法，但synchronized并不属于方法定义的一部分，
因此，synchronized关键字不能被继承。如果在父类中的某个方法使用了synchronized关键字，而在子类中覆盖了这个方法，在子类中的这个方法默认情况下并不是同步的，而必须显式地在子类的这个方法中加上synchronized关键字才可以。当然，还可以在子类方法中调用父类中相应的方法，这样虽然子类中的方法不是同步的，但子类调用了父类的同步方法，因此，子类的方法也就相当于同步了。

在定义接口方法时不能使用synchronized关键字。
构造方法不能使用synchronized关键字，但可以使用synchronized代码块来进行同步。

synchoronized修改静态方法：
syncThread1和syncThread2是SyncThread的两个对象，但在thread1和thread2并发执行时却保持了线程同步。这是因为run中调用了静态方法method，而静态方法是属于类的，所以syncThread1和syncThread2相当于用了同一把锁。这与Demo1是不同的。

Synchronized还可作用于一个类：
class ClassName {
   public void method() {
      synchronized(ClassName.class) {
         // todo
      }
   }
}//synchronized作用于一个类T时，是给这个类T加锁，T的所有对象用的是同一把锁

小结如下：

搞清楚synchronized锁定的是哪个对象，就能帮助我们设计更安全的多线程程序。

还有一些技巧可以让我们对共享资源的同步访问更加安全：

1． 定义private 的instance变量+它的 get方法，而不要定义public/protected的instance变量。如果将变量定义为public，对象在外界可以
绕过同步方法的控制而直接取得它，并改动它。这也是JavaBean的标准实现方式之一。

2． 如果instance变量是一个对象，如数组或ArrayList什么的，那上述方法仍然不安全，因为当外界对象通过get方法拿到这个instance对象
的引用后，又将其指向另一个对象，那么这个private变量也就变了，岂不是很危险。 这个时候就需要将get方法也加上synchronized同步，并
且，只返回这个private对象的clone()――这样，调用端得到的就是对象副本的引用了

}



Java中设置最大堆和最小堆内存的参数是什么？

volatile的作用？
{
  用volatile修饰后的变量不允许有不同于“主”内存区域的变量拷贝。换句话说，一个变量经 volatile修饰后在所有线程中必须是同步的；任何线程中改变了它的值，所有其他线程立即获取到了相同的值。
  理所当然的，volatile修饰的变量存取时比一般变量消耗的资源要多一点，因为线程有它自己的变量拷贝更为高效。

  在使用volatile关键字时要慎重，并不是只要简单类型变量使用volatile修饰，对这个变量的所有操作都是原来操作，当变量的值由自身的上一个决定时，如n=n+1、n++ 等，volatile关键字将失效，
  只有当变量的值和自身上一个值无关时对该变量的操作才是原子级别的，如n = m + 1，这个就是原级别的。所以在使用volatile关键时一定要谨慎，如果自己没有把握，可以使用synchronized来代替volatile。

  https://www.cnblogs.com/paddix/p/5428507.html
  提醒博主：按照JLS，除了long 和 double之外的类型，读写操作本身就是原子的，不需要通过volatile修饰。
  再进一步说，如果需要确保原子操作，使用AtomicLong之类的同步类更好，这个同步类内置了很多原子操作，包括自增和自减。
  再进一步说，唯一需要用到volatile的场合是为了避免活性失败，但是又不想用锁和同步类。
vs
  AtomicLong确实可以保证原子性，也提供了很多比较方便的方法。不过如果只是单纯的对long/double读/写的话，是可以用volatile的。
  至于volatile使用的唯一场景是“避免活性失败”，在jdk 1.5之前应该是，但是jdk 1.5之后，volatile的语义是有加强的，所以应用场景也有所扩大
  {
    实例化一个对象其实可以分为三个步骤：
  　　（1）分配内存空间。
  　　（2）初始化对象。
  　　（3）将内存空间的地址赋值给对应的引用
    但是由于操作系统可以对指令进行重排序，所以上面的过程也可能会变成如下过程：
  　　（1）分配内存空间。
  　　（2）将内存空间的地址赋值给对应的引用。
  　　（3）初始化对象

  　　如果是这个流程，多线程环境下就可能将一个未初始化的对象引用暴露出来，从而导致不可预料的结果。因此，为了防止这个过程的重排序，我们需要将变量设置为volatile类型的变量。

  可见性问题主要指一个线程修改了共享变量值，而另一个线程却看不到。引起可见性问题的主要原因是每个线程拥有自己的一个高速缓存区——线程工作内存。

  因为long和double两种数据类型的操作可分为高32位和低32位两部分，因此普通的long或double类型读/写可能不是原子的。因此，鼓励大家将共享的long和double变量设置为volatile类型，
  这样能保证任何情况下对long和double的单次读/写操作都具有原子性。

  必须同时满足下面两个条件才能保证在并发环境的线程安全：
　　（1）对变量的写操作不依赖于当前值。
　　（2）该变量没有包含在具有其他变量的不变式中。
    https://my.oschina.net/tantexian/blog/808032
  volatile关键字的两层语义

　　一旦一个共享变量（类的成员变量、类的静态成员变量）被volatile修饰之后，那么就具备了两层语义：
　　1）保证了不同线程对这个变量进行操作时的可见性，即一个线程修改了某个变量的值，这新值对其他线程来说是立即可见的。
　　2）禁止进行指令重排序。

  volatile的可见性，即任何时刻只要有任何线程修改了volatile变量的值，其他线程总能获取到该最新值

    内存屏障有两个能力：
    1. 阻止屏障两边的指令重排序
    2. 强制把写缓冲区/高速缓存中的脏数据等写回主内存，让缓存中相应的数据失效

    对Load Barrier来说，在读指令前插入读屏障，可以让高速缓存中的数据失效，重新从主内存加载数据
    对Store Barrier来说，在写指令之后插入写屏障，能让写入缓存的最新数据写回到主内存。
  }
  {
    https://blog.csdn.net/xilove102/article/details/52437581
    Java 语言中的 volatile 变量可以被看作是一种 “程度较轻的 synchronized”；与 synchronized 块相比，volatile 变量所需的编码较少，并且运行时开销也较少，
    但是它所能实现的功能也仅是 synchronized 的一部分。

    volatile的使用条件：
    volatile 变量具有 synchronized 的可见性特性，但是不具备原子特性。这就是说线程能够自动发现 volatile 变量的最新值。
    Volatile 变量可用于提供线程安全，但是只能应用于非常有限的一组用例：多个变量之间或者某个变量的当前值与修改后值之间没有约束。因此，单独使用 volatile 还不足以实现计数器、互斥锁或任何具有与多个变量相关的不变式（Invariants）的类
    （例如 “start <=end”）。

    出于简易性或可伸缩性的考虑，您可能倾向于使用 volatile 变量而不是锁。当使用 volatile 变量而非锁时，某些习惯用法（idiom）更加易于编码和阅读。此外，volatile 变量不会像锁那样造成线程阻塞，
    因此也很少造成可伸缩性问题。在某些情况下，如果读操作远远大于写操作，volatile 变量还可以提供优于锁的性能优势。

    {
    https://blog.csdn.net/hxpjava1/article/details/55188908
    https://www.ibm.com/developerworks/cn/java/j-jtp06197.html
      volatile的适用场景
      模式 #1：状态标志
      也许实现 volatile 变量的规范使用仅仅是使用一个布尔状态标志，用于指示发生了一个重要的一次性事件，例如完成初始化或请求停机。
        volatile boolean shutdownRequested;
        ...

        public void shutdown() {
           shutdownRequested = true;
        }
        public void doWork() {
           while (!shutdownRequested) {
               // do stuff
           }
        }
        线程1执行doWork()的过程中，可能有另外的线程2调用了shutdown，所以boolean变量必须是volatile。
        而如果使用 synchronized 块编写循环要比使用 volatile 状态标志编写麻烦很多。由于 volatile 简化了编码，并且状态标志并不依赖于程序内任何其他状态，因此此处非常适合使用 volatile。
        这种类型的状态标记的一个公共特性是：通常只有一种状态转换；shutdownRequested 标志从false 转换为true，然后程序停止。这种模式可以扩展到来回转换的状态标志，但是只有在转换周期不被察觉的情况下
        才能扩展（从false 到true，再转换到false）。此外，还需要某些原子状态转换机制，例如原子变量


        模式 #2：一次性安全发布（one-time safe publication）

        在缺乏同步的情况下，可能会遇到某个对象引用的更新值（由另一个线程写入）和该对象状态的旧值同时存在。

        这就是造成著名的双重检查锁定（double-checked-locking）问题的根源，其中对象引用在没有同步的情况下进行读操作，产生的问题是您可能会看到一个更新的引用，但是仍然会通过该引用看到不完全构造的对象。参见：【设计模式】5. 单例模式（以及多线程、无序写入、volatile对单例的影响）
        //注意volatile！！！！！！！！！！！！！！！！！
          private volatile static Singleton instace;

          public static Singleton getInstance(){
              //第一次null检查
              if(instance == null){
                  synchronized(Singleton.class) {    //1
                      //第二次null检查
                      if(instance == null){          //2
                          instance = new Singleton();//3
                      }
                  }
              }
              return instance;


        如果不用volatile，则因为内存模型允许所谓的“无序写入”，可能导致失败。——某个线程可能会获得一个未完全初始化的实例。

        考察上述代码中的 //3 行。此行代码创建了一个 Singleton 对象并初始化变量 instance 来引用此对象。这行代码的问题是：在Singleton 构造函数体执行之前，变量instance 可能成为非 null 的！
        什么？这一说法可能让您始料未及，但事实确实如此。

        在解释这个现象如何发生前，请先暂时接受这一事实，我们先来考察一下双重检查锁定是如何被破坏的。假设上述代码执行以下事件序列：

              线程 1 进入 getInstance() 方法。
              由于 instance 为 null，线程 1 在 //1 处进入synchronized 块。
              线程 1 前进到 //3 处，但在构造函数执行之前，使实例成为非null。
              线程 1 被线程 2 预占。
              线程 2 检查实例是否为 null。因为实例不为 null，线程 2 将instance 引用返回，返回一个构造完整但部分初始化了的Singleton 对象。
              线程 2 被线程 1 预占。
              线程 1 通过运行 Singleton 对象的构造函数并将引用返回给它，来完成对该对象的初始化。


        模式 #3：独立观察（independent observation）

        安全使用 volatile 的另一种简单模式是：定期 “发布” 观察结果供程序内部使用。【例如】假设有一种环境传感器能够感觉环境温度。一个后台线程可能会每隔几秒读取一次该传感器，并更新包含当前文档的 volatile 变量。然后，其他线程可以读取这个变量，从而随时能够看到最新的温度值。

        使用该模式的另一种应用程序就是收集程序的统计信息。【例】如下代码展示了身份验证机制如何记忆最近一次登录的用户的名字。将反复使用lastUser 引用来发布值，以供程序的其他部分使用。
        public class UserManager {
              public volatile String lastUser; //发布的信息

              public boolean authenticate(String user, String password) {
                  boolean valid = passwordIsValid(user, password);
                  if (valid) {
                      User u = new User();
                      activeUsers.add(u);
                      lastUser = user;
                  }
                  return valid;
              }
          }


        模式 #4：“volatile bean” 模式

        volatile bean 模式的基本原理是：很多框架为易变数据的持有者（例如 HttpSession）提供了容器，但是放入这些容器中的对象必须是线程安全的。

        在 volatile bean 模式中，JavaBean 的所有数据成员都是 volatile 类型的，并且 getter 和 setter 方法必须非常普通——即不包含约束！
          @ThreadSafe
          public class Person {
              private volatile String firstName;
              private volatile String lastName;
              private volatile int age;

              public String getFirstName() { return firstName; }
              public String getLastName() { return lastName; }
              public int getAge() { return age; }

              public void setFirstName(String firstName) {
                  this.firstName = firstName;
              }

              public void setLastName(String lastName) {
                  this.lastName = lastName;
              }

              public void setAge(int age) {
                  this.age = age;
              }
          }

        模式 #5：开销较低的“读－写锁”策略

        如果读操作远远超过写操作，您可以结合使用内部锁和 volatile 变量来减少公共代码路径的开销。

        如下显示的线程安全的计数器，使用 synchronized 确保增量操作是原子的，并使用 volatile 保证当前结果的可见性。如果更新不频繁的话，该方法可实现更好的性能，因为读路径的开销仅仅涉及 volatile 读操作，这通常要优于一个无竞争的锁获取的开销。

          @ThreadSafe
          public class CheesyCounter {
              // Employs the cheap read-write lock trick
              // All mutative operations MUST be done with the 'this' lock held
              @GuardedBy("this") private volatile int value;

              //读操作，没有synchronized，提高性能
              public int getValue() {
                  return value;
              }

              //写操作，必须synchronized。因为x++不是原子操作
              public synchronized int increment() {
                  return value++;
              }

        使用锁进行所有变化的操作，使用 volatile 进行只读操作。
        其中，锁一次只允许一个线程访问值，volatile 允许多个线程执行读操作

    }
  }
}

一道设计题

多个线程同时读写，读线程的数量远远于写线程，你认为应该如何解决 并发的问题？你会选择加什么样的锁？
{
  读写锁,分为读锁和写锁,多个读锁不互斥,读锁和写锁互斥,写锁与写锁互斥,这是JVM自己控制的,你只要上好相应的锁即可,如果你的代码只读数据,可以很多人同时读,但不能同时写,那就上读锁;
  如果你的代码修改数据,只能有一个人在写,且不能同时读取,那就上写锁.总之,读的时候上读锁,写的时候上写锁
}
{
  await()/signal()与wait()/notify()的区别：

    wait()和notify()必须在synchronized的代码块中使用 因为只有在获取当前对象的锁时才能进行这两个操作 否则会报异常 而await()和signal()一般与Lock()配合使用。
    wait是Object的方法，而await只有部分类有，如Condition。
    await()/signal()和新引入的锁定机制Lock直接挂钩，具有更大的灵活性。

除了synchronized关键字之外，你是怎么来保障线程安全的？

  那么为什么有了synchronized还要提出Lock呢？
  1.2.1 对synchronized的改进
    synchronized并不完美，它有一些功能性的限制 —— 它无法中断一个正在等候获得锁的线程，也无法通过投票得到锁，如果不想等下去，也就没法得到锁。
    同步还要求锁的释放只能在与获得锁所在的堆栈帧相同的堆栈帧中进行，多数情况下，这没问题（而且与异常处理交互得很好），但是，确实存在一些非块结构的锁定更合适的情况。

  与Lock相比synchronized还是存在一些缺陷的：虽然synchronized提供了便捷性的隐式获取锁释放锁机制（基于JVM机制），但是它却缺少了获取锁与释放锁的可操作性，可中断、超时获取锁，
  且它为独占式在高并发场景下性能大打折扣。

    1.2.2 ReentrantLock 类
  java.util.concurrent.lock 中的 Lock 框架是锁定的一个抽象，它允许把锁定的实现作为 Java 类，而不是作为语言的特性来实现(更加面向对象)。这就为 Lock 的多种实现留下了空间，
  各种实现可能有不同的调度算法、性能特性或者锁定语义。 ReentrantLock 类实现了 Lock ，它拥有与 synchronized 相同的并发性和内存语义，但是添加了类似锁投票、定时锁等候和可中断锁等候的一些特性。
  此外，它还提供了在激烈争用情况下更佳的性能。（换句话说，当许多线程都想访问共享资源时，JVM 可以花更少的时候来调度线程，把更多时间用在执行线程上。）

  reentrant 锁意味着什么呢？简单来说，它有一个与锁相关的获取计数器，如果拥有锁的某个线程再次得到锁，那么获取计数器就加1，然后锁需要被释放两次才能获得真正释放(重入锁)。
  这模仿了 synchronized 的语义；如果线程进入由线程已经拥有的监控器保护的 synchronized 块，就允许线程继续进行，当线程退出第二个（或者后续） synchronized 块的时候，不释放锁，
  只有线程退出它进入的监控器保护的第一个synchronized 块时，才释放锁。

  与目前的 synchronized 实现相比，争用下的 ReentrantLock 实现更具可伸缩性。（在未来的 JVM 版本中，synchronized 的争用性能很有可能会获得提高。）这意味着当许多线程都在争用同一个锁时，
  使用 ReentrantLock 的总体开支通常要比 synchronized 少得多.

  1.2.3什么时候选择用 ReentrantLock 代替 synchronized
  在 Java1.5 中，synchronized 是性能低效的。因为这是一个重量级操作，需要调用操作接口，导致有可能加锁消耗的系统时间比加锁以外的操作还多。相比之下使用 Java 提供的 Lock 对象，
  性能更高一些。但是到了 Java1.6，发生了变化。synchronized 在语义上很清晰，可以进行很多优化，有适应自旋，锁消除，锁粗化，轻量级锁，偏向锁等等。
  导致在 Java1.6 上 synchronized 的性能并不比 Lock 差。官方也表示，他们也更支持 synchronized，在未来的版本中还有优化余地。
  所以在确实需要一些 synchronized 所没有的特性的时候，比如时间锁等候、可中断锁等候、无块结构锁、多个条件变量或者锁投票使用ReentrantLock。ReentrantLock 还具有可伸缩性的好处，
  应当在高度争用的情况下使用它，但是请记住，大多数 synchronized 块几乎从来没有出现过争用，所以可以把高度争用放在一边。我建议用 synchronized 开发，直到确实证明 synchronized 不合适，
  而不要仅仅是假设如果使用 ReentrantLock “性能会更好”。请记住，这些是供高级用户使用的高级工具。（而且，真正的高级用户喜欢选择能够找到的最简单工具，直到他们认为简单的工具不适用为止。）。
  一如既往，首先要把事情做好，然后再考虑是不是有必要做得更快。
https://www.cnblogs.com/jiangyang/p/6007030.html
}
多线程一些点：http://www.cnblogs.com/xrq730/p/5060921.html

JAVA的AQS是否了解，它是嘛的？
{
  https://segmentfault.com/a/1190000008471362
  AQS，即AbstractQueuedSynchronizer, 队列同步器，它是Java并发用来构建锁和其他同步组件的基础框架。
  AQS是一个抽象类，主是是以继承的方式使用。AQS本身是没有实现任何同步接口的，它仅仅只是定义了同步状态的获取和释放的方法来供自定义的同步组件的使用。
  从图中可以看出，在java的同步组件中，AQS的子类（Sync等）一般是同步组件的静态内部类，即通过组合的方式使用。

  AQS定义了一套多线程访问共享资源的同步器框架，许多同步类实现都依赖于它，如常用的ReentrantLock/Semaphore/CountDownLatch.

  以CountDownLatch以例，任务分为N个子线程去执行，state也初始化为N（注意N要与线程个数一致）。这N个子线程是并行执行的，每个子线程执行完后countDown()一次，state会CAS减1。
  等到所有子线程都执行完后(即state=0)，会unpark()主调用线程，然后主调用线程就会从await()函数返回，继续后余动作。
  以ReentrantLock为例，state初始化为0，表示未锁定状态。A线程lock()时，会调用tryAcquire()独占该锁并将state+1。此后，其他线程再tryAcquire()时就会失败，
  直到A线程unlock()到state=0（即释放锁）为止，其它线程才有机会获取该锁。当然，释放锁之前，
  A线程自己是可以重复获取此锁的（state会累加），这就是可重入的概念。但要注意，获取多少次就要释放多么次，这样才能保证state是能回到零态的。

https://www.cnblogs.com/waterystone/p/4920797.html



  CAS(Compare-And-Swap) 算法是硬件对于并发的支持,针对多处理器操作而设计的处理器中的一种特殊指令,用于
  管理对共享数据的并发访问;
  CAS 是一种无锁的非阻塞算法的实现;
  CAS 包含了三个操作数:
  需要读写的内存值: V
  进行比较的预估值: A
  拟写入的更新值: B
  当且仅当 V == A 时, V = B, 否则,将不做任何操作;

  在 Java 5.0 提供了 java.util.concurrent(简称JUC)包,在此包中增加了在并发编程中很常用的工具类,
  用于定义类似于线程的自定义子系统,包括线程池,异步 IO 和轻量级任务框架;还提供了设计用于多线程上下文中
  的 Collection 实现等;
}

什么时候需要加volatile关键字？它能保证线程安全吗？

面试题集锦：http://www.cclycs.com/m344369.html
http://www.sohu.com/a/226988602_231667
多线程：http://www.cnblogs.com/xrq730/p/5060921.html

B公司

1.：“请你自我介绍一下”

2.：“你有什么业余爱好？”

3.：“你认为你工作中的哪些方面是最重要的？”

4.：“谈谈你的缺点”

5.：“谈一谈你的一次失败经历”

6.：“你为什么选择我们公司？”

7.：“对这项工作，你有哪些可预见的困难？”

8.：“我们为什么要录用你？”

9.：“您在前一家公司的离职原因是什么？”

博客：https://my.csdn.net/zhxdick
https://blog.csdn.net/antony9118/article/details/51375662
对于GC的理解，主要为了定位生产上应用性能瓶颈。现在你可能看这些都比较抽象，不过别急。可以思考下，为什么需要两个survivor？这个对于以后设计程序有好处，还有4.2那里的垃圾回收器很重要，
你的表格里面有些内容不完整，一般的我们高吞吐量的应用需要在新生代使用并行回收器来增加吞吐量。在你写的JAVA性能优化部分：第一点很对，但大多数情况下，写出一个能运行一个月内存不明显增长的Java程序很难。
这时我们需要灵活运用池化的思想。可以看下common-pool2这个包的源代码，这种池化大部分情况下是为了线程安全。final也大部分为了线程安全，Java需要考虑多线程安全就是因为它的对象是可变的。
像clojure这种不可变函数式语言就没有问题。下面思考下，什么是吞吐量？为什么需要多线程？为什么多线程会有安全问题？为什么线程上下文切换会有性能损耗？保证线程安全的方法。

面经：http://www.cnblogs.com/zuoxiaolong/p/life48.html
C公司
{
  TreeMap和LinkedHashMap是如何保证它的顺序的，哪种实现更好？
  {
    TreeMap：能够把它保存的记录根据键(key)排序,默认是按升序排序，也可以指定排序的比较器，该映射根据其键的自然顺序进行排序，或者根据创建映射时提供的 Comparator 进行排序，具体取决于使用的构造方法。
    HashMap的值是没有顺序的，它是按照key的HashCode来实现的，根据键可以直接获取它的值，具有很快的访问速度。HashMap最多只允许一条记录的键为Null(多条会覆盖);允许多条记录的值为 Null。非同步的。

    LinkedHashMap重写了Entry实现类，实现成双向链表的类型结构，会存取borfer和after的元素，插入的时候把当前元素插入到链表头部，
    继承自HashMap，一个有序的Map接口实现，这里的有序指的是元素可以按插入顺序或访问顺序排列；
    与HashMap的异同：同样是基于散列表实现，区别是，LinkedHashMap内部多了一个双向循环链表的维护，该链表是有序的，可以按元素插入顺序或元素最近访问顺序(LRU)排列
  }

  LinkedHashMap 继承自 HashMap，具有高效性，同时在 HashMap 的基础上，又在内部增加了一个链表，用以存放元素的顺序。
  TreeMap 则提供了一种完全不同的 Map 实现。从功能上讲，TreeMap 有着比 HashMap 更为强大的功能，它实现了 SortedMap 接口，这意味着它可以对元素进行排序。
  TreeMap 的性能略微低于 HashMap。如果在开发中需要对元素进行排序，那么使用 HashMap 便无法实现这种功能，使用 TreeMap 的迭代输出将会以元素顺序进行
  LinkedHashMap 是根据元素增加或者访问的先后顺序进行排序，而 TreeMap 则根据元素的 Key 进行排序。

}

1.你知道哪些或者你们线上使用什么GC策略? 它有什么优势，适用于什么 场景？
https://blog.csdn.net/qq_33780166/article/details/56831125
http://www.cnblogs.com/redcreen/archive/2011/05/04/2037029.html
2.JAVA类加载器包括几种？它们之间的关系是怎么样的？双亲委派机 制是什么意思？有什么好处？

3.如何定义个类加载器？你使用过哪些或者你在什么场景下需要定义的类加载器？
https://www.cnblogs.com/szlbm/p/5504631.html

4. PermSpace中保存什么数据? 会引起OutOfMemory吗？
5.做gc时，对象在内存各个Space中被移动的顺序是什么？

6.你有没有遇到过OutOfMemory问题？你是怎么来处理这个问题的？处理 过程中有哪些收获？

7.1.8之后Perm Space有哪些变动? MetaSpace默认是限的么? 还是 你们会通过什么方式来指定?
https://blog.csdn.net/zhyhang/article/details/17246223/

8.Jstack是什么的? Jstat呢? 如果线上程序周期性地出现卡顿，你怀疑可 能是gc

导致的，你会怎么来排查这个问题？线程日志一般你会看其中的什么 部分？

9.StackOverFlow异常有没有遇到过？一般你猜测会在什么情况下被触 发？

如何指定一个线程的堆栈？一般你们写多少？
----
系统jvm的stack空间占满了，爆出了stackOverflow异常。
只好修改Stack Space的大小：启动参数加入：-Xss512k 参数来解决。

捕获异常，是非常危险的，如果不能处理的更好的话，抛出异常更好。
https://www.cnblogs.com/thirtyfive16/p/6088910.html
----
Thread(ThreadGroup group, Runnable target, String name, long stackSize)
分配新的 Thread 对象，以便将 target 作为其运行对象，将指定的 name 作为其名称，作为 group 所引用的线程组的一员，并具有指定的堆栈大小。

在JVM中，栈是针对线程的，在线程构造函数中，我们可以看到可以传入栈的大小，需要注意的是，该值对JVM而言只是一个建议，JVM有权选择更合适的值
Java代码  收藏代码
public Thread(ThreadGroup group, Runnable target, String name,
                  long stackSize) {
    init(group, target, name, stackSize);
}
     当然也可以通过JVM启动参数来指定
-XX:ThreadStackSize=<value>:设置线程的栈大小（字节数）(0表示默认) [Sparc: 512, Solaris Intel: 256, Sparc 64bit: 1024 all others 0]
    一般情况下采用默认的值即可


并发、JVM、分布式、
TCP/IP协议: https://www.cnblogs.com/onepixel/p/7092302.html
https://blog.csdn.net/u011318165/article/details/48102939

1）LinkedList，ArrayList，HashMap，TreeMap

HashMap是不是有序的？不是

有没有有顺序的Map实现类？有TreeMap和LinkedHashMap。

TreeMap和LinkedHashMap是如何保证它的顺序的？哪个的有序实现比较好？还有没有比它更好或者更高效的实现方式？
----
Map主要用于存储健值对，根据键得到值，因此不允许键重复(重复了覆盖了),但允许值重复。 Hashmap 是一个最常用的Map,它根据键的HashCode 值存储数据,根据键可以直接获取它的值，具有很快的访问速度，
遍历时，取得数据的顺序是完全随机的。HashMap最多只允许一条记录的键为Null;允许多条记录的值为 Null;HashMap不支持线程的同步，即任一时刻可以有多个线程同时写HashMap;可能会导致数据的不一致。
如果需要同步，可以用 Collections的synchronizedMap方法使HashMap具有同步的能力，或者使用ConcurrentHashMap。 Hashtable与 HashMap类似,它继承自Dictionary类，
不同的是:它不允许记录的键或者值为空;它支持线程的同步，即任一时刻只有一个线程能写Hashtable,因此也导致了 Hashtable在写入时会比较慢。 LinkedHashMap保存了记录的插入顺序，
在用Iterator遍历LinkedHashMap时，先得到的记录肯定是先插入的.也可以在构造时用带参数，按照应用次数排序。在遍历的时候会比HashMap慢，不过有种情况例外，当HashMap容量很大，实际数据较少时，
遍历起来可能会比LinkedHashMap慢，因为LinkedHashMap的遍历速度只和实际数据有关，和容量无关，而HashMap的遍历速度和他的容量有关。 TreeMap实现SortMap接口，能够把它保存的记录根据键排序,
默认是按键值的升序排序，也可以指定排序的比较器，当用Iterator 遍历TreeMap时，得到的记录是排过序的。

一般情况下，我们用的最多的是HashMap,HashMap里面存入的键值对在取出的时候是随机的,它根据键的HashCode值存储数据,根据键可以直接获取它的值，具有很快的访问速度。在Map 中插入、删除和定位元素，
HashMap 是最好的选择。 TreeMap取出来的是排序后的键值对。但如果您要按自然顺序或自定义顺序遍历键，那么TreeMap会更好。 LinkedHashMap 是HashMap的一个子类，如果需要输出的顺序和输入的相同,
那么用LinkedHashMap可以实现,它还可以按读取顺序来排列，像连接池中可以应用。
----
2）Java并发包当中的类，它们都有哪些作用，以及它们的实现原理，这些类就是java.concurrent包下面
{
  java并发指南:一系列博客 http://tutorials.jenkov.com/java-concurrency/index.html

}

所有的线程一起等待某个事件的发生，当某个事件发生时，所有线程一起开始往下执行的话，有什么好的办法吗？
https://blog.csdn.net/defonds/article/details/44021605/
这个时候你可能会说可以用栅栏（Java的并发包中的CyclicBarrier），那么面试官就会继续问你，你知道它的实现原理吗？
----
java.util.concurrent.CyclicBarrier 类是一种同步机制，它能够对处理一些算法的线程实现同步。换句话讲，它就是一个所有线程必须等待的一个栅栏，直到所有线程都到达这里，然后所有线程才可以继续做其他事情.

1. 在创建一个 CyclicBarrier 的时候你需要定义有多少线程在被释放之前等待栅栏。创建 CyclicBarrier 示例：
CyclicBarrier barrier = new CyclicBarrier(2);

2. 如何让一个线程等待一个 CyclicBarrier：
barrier.await();
也可以为等待线程设定一个超时时间。等待超过了超时时间之后，即便还没有达成 N 个线程等待 CyclicBarrier 的条件，该线程也会被释放出来。以下是定义超时时间示例：
barrier.await(10, TimeUnit.SECONDS);

满足以下任何条件都可以让等待 CyclicBarrier 的线程释放：
最后一个线程也到达 CyclicBarrier(调用 await());
当前线程被其他线程打断(其他线程调用了这个线程的 interrupt() 方法);
其他等待栅栏的线程被打断;
其他等待栅栏的线程因超时而被释放;
外部线程调用了栅栏的 CyclicBarrier.reset() 方法;

CyclicBarrier 支持一个栅栏行动，栅栏行动是一个 Runnable 实例，一旦最后等待栅栏的线程抵达，该实例将被执行。你可以在 CyclicBarrier 的构造方法中将 Runnable 栅栏行动传给它：
Runnable      barrierAction = ... ;
CyclicBarrier barrier       = new CyclicBarrier(2, barrierAction);
----
你还知道其它的实现方式吗？
{
  实现依赖：
  1、lock 可重入锁 ReentrantLock
  2、Condition 条件谓词。

  实现思路：就是设置一个计数，每当有线程达到时，计数count-1，Condition.await 进入阻塞， 当count =0，那么可以 signalAll ，让所有线程得以唤醒。 唤醒后立马重置！
  http://wangxinchun.iteye.com/blog/1883502 源码分析


}

哪个方式更好？

还有比它更好的实现方式吗？

{
  栅栏类似闭锁,但是它们是有区别的.
  闭锁用来等待事件，而栅栏用于等待其他线程.什么意思呢?就是说闭锁用来等待的事件就是countDown事件,只有该countDown事件执行后所有之前在等待的线程才有可能继续执行;
  而栅栏没有类似countDown事件控制线程的执行,只有线程的await方法能控制等待的线程执行.

  CyclicBarrier强调的是n个线程，大家相互等待，只要有一个没完成，所有人都得等着。
  barrier 在释放等待线程后可以重用，所以称它为循环 的 barrier。

}
{
  1. java.util.concurrent.locks.ReadWriteLock 读写锁是一种先进的线程锁机制。它能够允许多个线程在同一时间对某特定资源进行读取，但同一时间内只能有一个线程对其进行写入。
  读写锁的理念在于多个线程能够对一个共享资源进行读取，而不会导致并发问题。并发问题的发生场景在于对一个共享资源的读和写操作的同时进行，或者多个写操作并发进行。
  本节只讨论 Java 内置 ReadWriteLock。如果你想了解 ReadWriteLock 背后的实现原理，请参考我的《Java 并发指南》主题中的《读写锁》小节。
  ReadWriteLock 锁规则

  一个线程在对受保护资源在读或者写之前对 ReadWriteLock 锁定的规则如下：
  读锁：如果没有任何写操作线程锁定 ReadWriteLock，并且没有任何写操作线程要求一个写锁(但还没有获得该锁)。因此，可以有多个读操作线程对该锁进行锁定。
  写锁：如果没有任何读操作或者写操作。因此，在写操作的时候，只能有一个线程对该锁进行锁定。
  ReadWriteLock 实现

  ReadWriteLock 是个接口，如果你想用它的话就得去使用它的实现类之一。java.util.concurrent.locks 包提供了 ReadWriteLock 接口的以下实现类：
  ReentrantReadWriteLock

  2. CopyOnWriteArrayList & CopyOnWriteArraySet是并发容器，适合读多写少的场景，如网站的黑白名单设置。缺点是内存占用大，数据一致性的问题，CopyOnWrite容器只能保证数据最终的一致性，
  不能保证数据实时一致性。鉴于它的这些缺点，可以使用ConcurrentHashMap容器。
  实现原理：新增到容器的数据会放到一个新的容器中，然后将原容器的引用指向新容器，旧容器也会存在，因此会有两个容器占用内存。我们也可以用同样的方式实现自己的CopyOnWriteMap。

  3. CountDownLatch
  CountDownLatch和CyclicBarrier有点类似，但是还是有些区别的。CountDownLatch也是一个同步辅助类，它允许一个或者多个线程一直等待，直到正在其他线程中执行的操作完成。
  它是等待正在其他线程中执行的操作，并不是线程之间相互等待。CountDownLatch初始化时需要给定一个计数值，每个线程执行完之后，必须调用countDown()方法使计数值减1，直到计数值为0，
  此时等待的线程才会释放。

  4. ConcurrentHashMap

  ConcurrentHashMap同样是一个并发容器，将同步粒度最小化。

  实现原理：ConcurrentHashMap默认是由16个Segment组成，每个Segment由多个Hashtable组成，数据变更需要经过两次哈希算法，第一次哈希定位到Segment，第二次哈希定位到Segment下的Hashtable，
  容器只会将单个Segment锁住，然后操作Segment下的Hashtable，多个Segment之间不受影响。如果需要扩容不是对Segment扩容而是对Segment下的Hashtable扩容。虽然经过两次哈希算法会使效率降低，
  但是比锁住整个容器效率要高得多。

  5. BlockingQueue

  BlockingQueue只是一个接口，它的实现类有ArrayBlockingQueue、LinkedBlockingQueue、PriorityBlockingQueue、SynchronousQueue、DelayQueue、LinkedBlockingDeque。

  ArrayBlockingQueue：由数据支持的有界阻塞队列。

  LinkedBlockingQueue：基于链接节点、范围任意的阻塞队列。

  PriorityBlockingQueue：无界阻塞队列。

  SynchronousQueue：一种阻塞队列，其中每个插入操作必须等待另一个线程的对应移除操作。

  DelayQueue：Delayed元素的一个无界阻塞队列。

  LinkedBlockingDeque：基于链接节点、范围任意的双端阻塞队列，可以在队列的两端添加、移除元素。

  6. Lock

  Lock分为公平锁和非公平锁，默认是非公平锁。实现类有ReetrantLock、ReetrantReadWriteLock，都依赖于AbstractQueuedSynchronizer抽象类。ReetrantLock将所有Lock接口的操作都委派到Sync类上，
  Sync有两个子类：NonFairSync和FaiSync，通过其命名就能知道分别处理非公平锁和公平锁的。AbstractQueuedSynchronizer把所有请求构成一个CLH队列，这里是一个虚拟队列，当有线程竞争锁时，
  该线程会首先尝试是否能获取锁，这种做法对于在队列中等待的线程来说是非公平的，如果有线程正在Running，那么通过循环的CAS操作将此线程增加到队尾，直至添加成功。

  7. Atomic包

  Atomic包下的类实现了原子操作，有对基本类型如int、long、boolean实现原子操作的类：AtomicInteger、AtomicLong、AtomicBoolean，如果需要对一个对象进行原子操作，
  也有对对象引用进行原子操作的AtomicReference类，还有对对象数组操作的原子类：AtomicIntegerArray、AtomicLongArray、AtomicReferenceArray。原子操作核心思想是CAS操作，
  然后调用底层操作系统指令来实现。

}

//java nio io面试题
3）IO包（可能略）和NIO包（重点）中的内容。

熟悉NIO模型，selector职责和实现原理（非常清楚）。

NIO的核心是IO线程池。

IO包的设计模式（装饰器模式），为什么要这样设计？
其实NIO的核心是IO线程池，一定要记住这个关键点。
有的面试官还会问你有没有更好的设计，这个时候如果你不知道请果断说自己现在的水平有限，想不出来更好的设计，千万不要信口开河，随意YY。

4）Java的虚拟机的内容。这部分主要包括三部分，GC、类加载机制，以及内存。

什么时候一个对象会被GC？

为什么要在这种时候对象才会被GC？

GC策略都有哪些分类？分别都有什么优劣势？都适用于什么场景？

举个实际的场景，选择一个GC策略？为什么要选择这个策略？

Java类加载器都有哪些？

每个类加载器都加载哪些类？

这些类加载之间的父子关系是怎样的？

什么是双亲委派模型？为什么Java类加载器要使用双亲委派模型？

如何自定义自己的类加载器，它和Java自带的类加载器关系如何处理？

内存

内存分为哪几部分，分别都存储哪些数据？

一个对象从创建到销毁，怎么在这些里存活和转移的？

内存的哪些部分会参与GC的回收？

Java的内存模型是怎么设计的？为什么要这么设计？

结合内存模型的设计谈谈volatile关键字的作用？

你在谈的时候，肯定会提到可见性，那么接着可见性这三个字，还可以继续问你并发的内容。

2、讲述自己的项目，并在中间穿插着问题

讲你做过的项目，为什么要这么做，挖掘出一个甚至N个亮点，让眼前一亮。

《程序员面经：面试前到底该不该刷题以及面试前该如何准备》

3、额外的加分项

TCP/IP协议、算法

1、计算机系统原理。

2、网络通信协议（TCP/IP，HTTP等）。

3、数据结构与算法。

4、著名开源项目的源码。

5、你自己有很棒的开源项目。

6、你的个人博客。

1-3项，如之前比较了解，临时抱佛脚。4-6项，需要日常的积累了。

社招面试如何准备

LZ会分为四个部分来谈论这个问题，由于LZ本身是Java出身，因此关于主语言的问题，都是与Java相关，其它语言的同学可以选择性忽略。此外，面试的时候一般面试官的问题都是环环相扣，逐渐深入的，这点在下面大家可以更明显的感受出来。

1、主语言本身以及它的高级特性。

主语言当然就是你平日里拿来赚钱的家伙。不要告诉LZ你没有主语言，你会N多种语言，或者是你精通N多种语言，你要非这么说的话，你可以来杭州试试，LZ保证不打死你，最多打残。

LZ的主语言很显然是Java，那么对于Java来说，它的语言本身以及它的高级特性，都有哪些比较容易在面试中问到呢？

一般情况下，主要有以下知识点很容易被问到。

1）Java的数据结构相关的类实现原理，比如LinkedList，ArrayList，HashMap，TreeMap这一类的。以下简单模拟一个数据结构的连环炮。

比如，面试官先问你HashMap是不是有序的？

你肯定回答说，不是有序的。那面试官就会继续问你，有没有有顺序的Map实现类？

你如果这个时候说不知道的话，那这个问题就到此结束了。如果你说有TreeMap和LinkedHashMap。

那么面试官接下来就可能会问你，TreeMap和LinkedHashMap是如何保证它的顺序的？

如果你回答不上来，那么到此为止。如果你依然回答上来了，那么面试官还会继续问你，你觉得它们两个哪个的有序实现比较好？

如果你依然可以回答的话，那么面试官会继续问你，你觉得还有没有比它更好或者更高效的实现方式？

如果你还能说出来的话，那么就你所说的实现方式肯定依然可以问你很多问题。

以上就是一个面试官一步一步提问的例子。所以，如果你了解的不多，千万不要敷衍，因为可能下一个问题你就暴露了，还不如直接说不会，把这个问题结束掉，赶紧切换到你熟悉的领域。

2）Java并发包当中的类，它们都有哪些作用，以及它们的实现原理，这些类就是java.concurrent包下面的。与上面一样，咱们也简单的模拟一个并发包的连环炮。

比如面试官可能会先问你，如果想实现所有的线程一起等待某个事件的发生，当某个事件发生时，所有线程一起开始往下执行的话，有什么好的办法吗？

这个时候你可能会说可以用栅栏，那么面试官就会继续问你，你知道它的实现原理吗？

如果你继续回答的话，面试官可能会继续问你，你还知道其它的实现方式吗？

如果你还能说出很多种实现方式的话，那么继续问你，你觉得这些方式里哪个方式更好？

如果你说出来某一个方式比较好的话，面试官依然可以继续问你，那如果让你来写的话，你觉得还有比它更好的实现方式吗？

如果你这个时候依然可以说出来你自己更好的实现方式，那么面试官肯定还会揪着这个继续问你。

为什么说面试的时候要引导面试官，原因就在这了。因为面试官的提问很多时候都是有迹可循的，你如果抓住了他的轨迹，能够猜到他下面很可能会问什么，那你在回答的时候就可以往你想要谈的方向去说。这样面试时就会显得更加从容，更加的游刃有余。

3）IO包和NIO包中的内容。这部分里面NIO会是重点，IO包大部分都会比较熟悉，因此可能会直接略过，直接问你NIO的内容。

IO包和NIO包的内容相对来说不是很多，首先NIO模型要熟悉，特别是其中的selector一定要非常清楚它的职责和实现原理。其实NIO的核心是IO线程池，一定要记住这个关键点。有的时候，面试官可能也会问你IO包的设计模式（装饰器模式），为什么要这样设计？

有的面试官还会问你有没有更好的设计，这个时候如果你不知道请果断说自己现在的水平有限，想不出来更好的设计，千万不要信口开河，随意YY。

4）Java的虚拟机的内容。这部分主要包括三部分，GC、类加载机制，以及内存。

一个GC部分简单的连环炮。

面试官可以先问你什么时候一个对象会被GC？

接着继续问你为什么要在这种时候对象才会被GC？

接着继续问你GC策略都有哪些分类？

你如果说出来了，继续问你这些策略分别都有什么优劣势？都适用于什么场景？

你继续说出来了以后，给你举个实际的场景，让你选择一个GC策略？

你如果选出来了，继续问你，为什么要选择这个策略？

下面是关于类加载机制的简单连环炮。

首先肯定是先问你Java的类加载器都有哪些？

回答了这些以后，可能会问你每个类加载器都加载哪些类？

说完以后，可能会问你这些类加载之间的父子关系是怎样的？

你在回答的时候可能会提到双亲委派模型，那么可以继续问你什么是双亲委派模型？

你解释完了以后，可能会继续问你，为什么Java的类加载器要使用双亲委派模型？

你回答完以后，可能会继续问你如何自定义自己的类加载器，自己的类加载器和Java自带的类加载器关系如何处理？

再来一个关于内存的连环炮。

首先肯定就是问你内存分为哪几部分，这些部分分别都存储哪些数据？

然后继续问你一个对象从创建到销毁都是怎么在这些部分里存活和转移的？

接着可能会问你，内存的哪些部分会参与GC的回收？

完事以后，可能还会问你Java的内存模型是怎么设计的？

你回答了以后，还会继续问你为什么要这么设计？

问完以后，还可能会让你结合内存模型的设计谈谈validate关键字的作用？

你在谈的时候，肯定会提到可见性，那么接着可见性这三个字，还可以继续问你并发的内容。

基本上Java语言本身以及语言稍微高级点的内容就是以上部分，如果你能把以上四部分了解的非常透彻，那基本上Java这部分就没啥问题了，因为光以上的内容就够你跟面试官聊很久了。你聊这些聊得久了，自然问你其它问题的时间就会短点。

你从LZ写这些问题的过程也应该能感受出来，很多时候，面试官都是顺着一条线一路问下去的，如果你觉得这条线你不熟悉的话，就要及时拐弯，引导面试官去问其它方面的问题。千万不要一直往下深入，直到自己跳不出来为止，那就尴了个尬了。

2、讲述自己的项目，并在中间穿插着问题

这一部分是面试过程中必问，也是聊得最久的一个阶段。除非你前面的语言部分非常扎实，扎实到面试官问了一两个小时，依旧没有探出你对语言本身的了解到底有多深。否则的话，你一定逃不过自己的项目这一关，而且一般情况下聊得时间不会太短。

这一部分内容，一般的模式就是你自己去讲你做过的项目，然后面试官会冷不丁的让你去解释其中某一部分，比如让你解释当时为什么要这么做，或者问你现在觉得有没有更好的办法。而这些穿插的问题，大部分与你的项目所用到的技术有关。而你需要做的，就是充分、再充分的去总结自己做过的项目（尤其是最近的一两个项目），挖掘出一个甚至N个亮点，以备于到时候可以让面试官产生眼前一亮的感觉。如果你能达到这种效果的话，基本上离你成功就不远了。

这部分内容由于和每个人自己的经历息息相关，因此这里也没法列举可能问到的问题。这篇文章《程序员面经：面试前到底该不该刷题以及面试前该如何准备》是LZ之前写的，里面大概讨论了下如何在面试前总结，有兴趣的可以去了解一下。

3、额外的加分项

上面两个阶段基本上是必问的，还有一些加分项。这些加分项中，有些内容面试官也会问你（比如TCP/IP协议、算法），但更多的是会先问你了解不了解，你了解的话再继续聊，不了解的话就直接略过了，不至于因为这种问题而直接把你打入地狱。

下面LZ列举一下这些加分项，如果可以的话，这些加分项还是要争取一下的。

计算机系统原理。

网络通信协议（TCP/IP，HTTP等）。

数据结构与算法。

著名开源项目的源码。

你自己有很棒的开源项目。

你的个人博客。

待评论区补充。

这几项当中，对于前1-3项，如果你之前就比较了解，只是由于时间问题忘记了的话，还是可以临时抱佛脚一下的。至于后面4-6项，就需要你日常的积累了，不是一时半会儿能做到的。如果你平日里没有积累，那么后面这三个加分项只能抛弃了。

4、与你职位相关的内容

其实这最后一项是对前面三项的补充，你应该尽量去主攻和你面试的职位相关的内容。比如你面试一个实时计算的职位，那么你的算法最好要厉害，对于著名的实时计算开源项目要熟悉，最好阅读过源码，而且还要对分布式系统有一定的见解。

因此，这个第4部分没有具体的内容，只是提醒你，如果你很明确自己的面试职位，最好在面试前准备的时候，尽量朝职位的需求方向靠拢，这样成功的可能性更大。

下面是小编整理的一整套系统的Java学习教程，进扣君羊：前面三位数是616中间是959后面是444即可免费领取一整套系统的Java学习教程！

======
工作两年正好是一个重要的时间节点。在这个时候我认为有几个比较重要的事情需要做：
1：建立自己的技术体系之前可能学的东西比较零散，比较杂，这个时候是该将所学有体系的组织起来。
2：基础。thinking in java 在啃几遍，jvm相关的东西再看看，框架的源码再拿出来翻翻，涉及到的设计模式是不是也重新温习一下。
数据结构，算法，网络也适当的看看。3：就是一些企业级的应用技术了。比如消息中间件，服务中间件，如何建立高可用的应用等。
这部分的内容需要去一个大一点的企业能力才能提升上来。
4：是积累人脉和行业经验。其实这个是很多技术人员都忽略的一个方面，但是又非常重要。
======

{
1 JVM: 内存分析与调优，类加载机制，字节码基本结构。2 并发：jdk自身的并发库; 第三方的库或者框架，akka,vertx,...3 jvm平台的潜力语言:Scala,groovy4 J2EE：基本概念:sevlet,jpa，...; 相关框架:spring,hibernate；容器:Jetty,tomcat5 Osgi6 Maven,gradle
http://www.offcn.com/it/2018/0123/18896_2.html

较多企业会希望Java工程师最好熟悉一点前端技术，前端与后端基数相结合，将有助于求职时提高获得offer的机会。

总的来说，企业更喜欢一专多能式职业技能人才，单一技能的前端/后端程序员已经不能满足企业的需求，而且事实上Java已经成为全栈前端和后端开发中最流行的语言，所以要学编程学习全栈开发，全栈开发包括Java开发。东时为真而来，历经多年时间研究探索推出前端HTML5+后端Java+数据库的多技能的全栈培训课程，力求为高中端企业打造掌控全局式全栈开发工程师。

https://www.jianshu.com/p/39a667b495cc
http://baijiahao.baidu.com/s?id=1588652546994154393&wfr=spider&for=pc
}

基础问题和思想：
1、抽象类和接口的区别（单纯的语法区别只能给一半分，要说出来适用场景）；
2、hashcode()和equals()的关系；
3、HashMap（Set）底层机制（用到的数据结构以及代码原理）；
4、Object的常用的一些方法；
5、讲一下反射以及用到的场景；
6、Spring 主要做了哪些工作（IOC 事务AOP 逻辑AOP等）；
7、IOC和AOP以及应用场景；
8、JVM的内存管理和GC；
9、OOM的解决方案（关联问题8）；
10、JVM ClassLoader原理；
11、怎么新开线程，线程安全怎么控制，ThreadLocal有什么用，HashMap怎么做到线程安全，怎么解决死锁的问题；
12、说几个常用的设计模式和应用场景；
13、java代理机制；
14、多服务器的session共享解决方案；
15、zookeeper的工作原理；
16、soa架构模式有什么好处；


数据库方面：
1、数据库连接池机制；
2、数据库隔离级别有哪些，mysql默认级别是哪个；
3、inner join、left join、right join、group by、having是怎么用的（给出2个表，手写查询语句）；
4、char和varchar的区别；
5、数据库方面的性能优化；
6、mysql的索引类型、区别、以及如何选取，画出btree是怎么存的，什么时候索引会失效
7、mysql表存储引擎有哪些，如何选取
8、分表的解决方案
9、hash分表怎么分

实战问题：
1、一个请求超过20秒了，你怎么排查和解决；
2、说说你觉得做的比较不错的项目，讲一下项目结构和用到的框架，再说一下为什么要选择这些框架；
3、“商品秒杀”的解决方案；
4、手写个单例模式出来；
5、分布式锁的解决方案
6、分布式事务解决方案
7、分布式环境下的定时任务管理

前端的一些问题，比如jquery的ajax的参数都是做什么用的，CSS框架和JS框架都用过哪些，怎么解决跨域的问题


1.有抽象方法且abstract标示就是抽象类,方法不具体但不要求一定要重写方法,抽象方法没有主体,接口全是抽象方法且实现之后全得重写,如listener和适配器,Action和ActionSupport
2.在set中的存储方式先判断hashcode是否相等,再判断equals是否相等,两个都相等,如果两个都相等视为相等
3.双列的HashSet,大概吧
4.toString ,equals,
5.接口增加了程序的灵活性,反射是比接口更加灵活的技术,可以抽象到任意的类,执行满足一些条件的方法,定义一个功能,可以使用class作为传参而不确定具体的类或者接口,可以是任何类,与接口比较相似,接口可以事先调用没写好的方法,而反射可以事先调用满足一些名字约束的方法
,而且反射可以使用私有的方法和字段
7.ioc:控制反转=di:注入,在struts中action的初始化由别的类完成,调用set方法而不是构造器给字段赋值,AOP:没学
8:当一个对象没有被栈中的变量指向时,也就是被系统判断无法再被使用,经过一段不确定的时间会被gc垃圾回收装置回收,通常使用varName=null;来手动释放内存,但不会马上被释放
11.继承Thread或者实现Runnable,重写run方法通过start开启多线程,多个线程操作同个数据时,那部分加上同步代码块,随便加个对象作为锁,或者给方法加上Synchornized,或者通过Lock类开锁解锁
,HashMap换HashTable,怎么解决死锁:别瞎写代码就不会死锁,就是别嵌套锁
12:单例模式:只能有一个对象,不知道有什么用,工厂模式:把创建对象的功能分出一个类:不知道有啥用
13:代理模式:代理类包含被代理类的对象的字段,代理类的构造函数传入被代理对象,在代理类写被代理类的同名方法,在此方法中调用原方法并在外部加以修改,如果要修改原方法内部,使用反射
:用途:和接口相似:接口是方法抽象,代理模式是对象抽象,对象不确定,由别人传入,或者是另一种情况:需要修改一个类的方法
6.9.10.14.15.16没听过


数据库
1.连接池:连接对象的集合,连接资源宝贵需要对连接管理 操作结束需要关闭连接 对象置空
建立一个连接要耗费资源 保持连接要耗费资源 连接池的意义就是对于常用的连接保持开启 ,超出数量的连接才创建和关闭
内置了一个list用于保存连接对象,自制的连接池就算放回了也可以继续使用的
3.只知道group by//分组查询 select * form 表 group by 列名 ,按一个的项分组,比如gender 男的一组女的一组,应该和其他条件比如count一起使用
having就是where,where在使用函数时无法使用换having
4,字符和字符串,char没用过,可能只能单字符吧
5.索引吧,建立索引,主键本身就是一个索引,其他不重复的列也可以作为索引,用索引作为条件查起来快,只知道这个
6.只记得一个索引类型是不重复
789不会


实战:
1.可能是服务器负荷过大,配置一个struts自带的拦截器execAndWite,当用户访问action时时间过长使其跳转到一个页面重复提交请求,可以让action先跳转到别的页面缩小问题的范围,或者先注释掉service的调用,同样是缩小问题范围
4:简单,所以具体代码就不写了,先私有化构造函数,class下声明自己实例的变量,在静态代码块或者直接在class下新建自己实例对象;在写个getInstance获得这个对象,懒汉式的就在方法内创建对象,如果为对象的字段为空就创建,不为空就直接返回这个对象好了
23567都不会,后面前端的东西不会


zookeeper常见面试题
zookeeper是如何保证事务的顺序一致性的
zookeeper采用了递增的事务Id来标识，所有的proposal都在被提出的时候加上了zxid，zxid实际上是一个64位的数字，高32位是epoch用来标识leader是否发生改变，如果有新的leader产生出来，epoch会自增，低32位用来递增计数。当新产生proposal的时候，会依据数据库的两阶段过程，首先会向其他的server发出事务执行请求，如果超过半数的机器都能执行并且能够成功，那么就会开始执行


zookeeper是如何选取主leader的？
当leader崩溃或者leader失去大多数的follower，这时zk进入恢复模式，


zk中znode类型有四种，持久化目录节点 持久化顺序编号目录节点(有顺序 能够在注册机器等许多场景用到) 临时目录节点 临时顺序编号节点
zk的通知机制
client端会对某个znode建立一个watcher事件，当该znode发生变化时，这些client会收到zk的通知，然后client可以根据znode变化来做出业务上的改变等。


zk的配置管理
程序分布式的部署在不同的机器上，将程序的配置信息放在zk的znode下，当有配置发生改变时，也就是znode发生变化时，可以通过改变zk中某个目录节点的内容，利用water通知给各个客户端 从而更改配置。
zk的命名服务
命名服务是指通过指定的名字来获取资源或者服务的地址，利用zk创建一个全局的路径，这个路径就可以作为一个名字，指向集群中的集群，提供的服务的地址，或者一个远程的对象等等。


分布式通知和协调
对于系统调度来说：操作人员发送通知实际是通过控制台改变某个节点的状态，然后zk将这些变化发送给注册了这个节点的watcher的所有客户端。
对于执行情况汇报：每个工作进程都在某个目录下创建一个临时节点。并携带工作的进度数据，这样汇总的进程可以监控目录子节点的变化获得工作进度的实时的全局情况。


机器中为什么会有master；
在分布式环境中，有些业务逻辑只需要集群中的某一台机器进行执行，其他的机器可以共享这个结果，这样可以大大减少重复计算，提高性能，于是就需要进行master选举。

redis面试题
https://www.cnblogs.com/jiahaoJAVA/p/6244278.html
https://www.cnblogs.com/Survivalist/p/8119891.html
